add_rules("mode.debug", "mode.release")

add_repositories("liteldev-repo https://github.com/LiteLDev/xmake-repo.git")
add_requires("expected-lite v0.8.0")
add_requires("levilamina develop", {configs = {target_type = "server"}})
add_requires("levibuildscript")

if not has_config("vs_runtime") then
    set_runtimes("MD")
end

target("Protocol")
    add_cxflags("/EHa", "/W4")
    add_files("src/**.cpp")
    add_includedirs("src")
    set_kind("static")
    set_languages("c++20")
    set_symbols("debug")
    add_defines("_HAS_CXX23=1","_AMD64_","NOMINMAX", "UNICODE", "WIN32_LEAN_AND_MEAN","Protocol")
    add_packages("expected-lite")

option("target_type")
    set_default("server")
    set_showmenu(true)
    set_values("server", "client")
option_end()

target("BinaryStreamTest")
    add_rules("@levibuildscript/linkrule")
    add_rules("@levibuildscript/modpacker")
    add_cxflags( "/EHa", "/utf-8", "/W4", "/w44265", "/w44289", "/w45263", "/w44738", "/w45204")
    add_defines("NOMINMAX", "UNICODE")
    add_headerfiles("src/(**.h)")
    add_includedirs("./src")
    add_files("src-test/BinaryStreamTest/**.cpp")
    set_kind("shared")
    add_packages("levilamina")
    add_shflags("/DELAYLOAD:bedrock_server.dll")
    set_exceptions("none")
    set_languages("c++20")
    set_symbols("debug")
    add_deps("Protocol")